routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ShippingChargeController;
use App\Http\Controllers\ShippingAreaController;
use App\Http\Controllers\FrontImageController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ExcelImportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

Route::get('/', function () {
    return view('front.wellcome');
});
// routes for mobile application
Route::get('/privacy-policy/app', function () {
	return view('privacy-policy');
});
Route::get('/terms-condition/app', function () {
	return view('termCondition');
});
		Route::post('login', [AuthController::class, 'login'])->name('custom.login');
		Route::post('register', [AuthController::class, 'register'])->name('user.register');
	
	
    Route::get('return-cashfree', [HomeController::class,'returnCashFree'])->name('return.cashefree');
	Route::post('notify-cashfree', [HomeController::class,'notifyPayment'])->name('notify.cashefree');
    Route::get('refresh/captcha', [HomeController::class, 'refreshCaptcha'])->name('refresh.captcha');
    Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');
   // Route::get('self-pickup', [HomeController::class, 'selfPickup'])->name('self.pickup');
    Route::get('time', [ShippingChargeController::class, 'timeCheck'])->name('get.time');
	Route::get('razorpay-create', [HomeController::class,'getRazorpayGateway'])->name('razorpay.payment.get');
    Route::middleware(['auth:sanctum', 'verified'])->group(function (){
	Route::get('dashboard', [HomeController::class, 'mainDashboard'])->name('dashboard');
	Route::get('address-data', [OrderController::class, 'addressData'])->name('address.data');
	Route::post('order-tracking', [OrderController::class, 'orderCreateTracking'])->name('create.order.tracking');
	Route::post('cancel', [OrderController::class, 'CancelOrder'])->name('order.status');
	Route::post('accept', [OrderController::class, 'acceptOrder'])->name('accept.order');
	Route::post('Shipping/vendor', [OrderController::class, 'shippingUpdate'])->name('shipping.update');
	Route::post('Shipping-address-update', [OrderController::class, 'shippingStatusUpdate'])->name('shipping-address-update');
	Route::get('/find-user/{id}/', [UserController::class, 'userName']);
	Route::resource('address', AddressController::class);
	//Route::get('address-edit', [AddressController::class, 'addressEdit'])->name('address.edit');
	Route::post('new-address-store', [AddressController::class, 'addressAdd'])->name('new.address.store');
	Route::get('user/edit/address/{id}', [AddressController::class, 'Editaddress'])->name('editadr');
	Route::get('user/delete/address/{id}', [AddressController::class, 'DeleteAddress'])->name('deleteadr');
	Route::post('add-delete', [HomeController::class, 'addDelete'])->name('add.delete');
     
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('order-item-{id}', [HomeController::class,'viewItems'])->name('views.items');
	Route::get('my-order/list', [OrderController::class, 'userOderList'])->name('user.order.list');
	Route::get('myprofile', [UserController::class, 'MyProfile'])->name('myprofile.index');
});
Route::middleware('admin')->group(function (){
		Route::get('export-product', [HomeController::class, 'exportProduct'])->name('export.product');
		Route::put('selfprofile/{id}', [HomeController::class, 'selfProfile'])->name('self.update');
	    Route::post('file-uplaod', [HomeController::class, 'uplaodFile'])->name('file.upload');
	    Route::delete('queries-destroy{id}', [HomeController::class, 'queryDestroy'])->name('query.destroy');
	    Route::get('update-status{id}', [HomeController::class, 'updateStatus'])->name('status.update.query');
	    
	    Route::get('query', [HomeController::class, 'queryIndex'])->name('query.index');
		Route::resource('area', ShippingAreaController::class);
		Route::resource('faqs', FaqController::class);
		Route::resource('frontimage', FrontImageController::class);
		Route::resource('charge', ShippingChargeController::class);
		Route::resource('user', UserController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('faqs.dataTable', [FaqController::class, 'faqdataTable'])->name('faqs.dataTable');
		Route::resource('brand', BrandController::class);
		Route::resource('category', CategoryController::class);
		Route::get('cat.dataTable', [CategoryController::class, 'dataTable'])->name('cat.dataTable');
		Route::resource('blog', BlogController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('blog-datatable', [BlogController::class, 'dataTable'])->name('blog.dataTable');
		Route::resource('product', ProductController::class);
		Route::get('product.dataTable', [ProductController::class, 'dataTable'])->name('product.dataTable');
		Route::get('get-variant', [ProductController::class, 'variantData'])->name('variant.get.data');
		Route::resource('settings', SettingsController::class);
		Route::post('settings/update', [SettingsController::class, 'update'])->name('setting.update');
		Route::resource('order', OrderController::class);
		Route::get('/product-variant/{pvt}/', [OrderController::class, 'variantName']);
		Route::resource('page', PageController::class);    
		Route::get('page-datatable', [PageController::class,'dataTable'])->name('page.dataTable');
		Route::post('images-file/{foldername}', [PageController::class,'uploadImages'])->name('page.imageupload');
		Route::get('variant.found', [OrderController::class, 'variantFound'])->name('variant.found');
        Route::get('order-invoice/{id}', [OrderController::class, 'orderinvoice'])->name('order.invoice');
		Route::get('order-dataTable', [OrderController::class, 'dataTable'])->name('order.dataTable');
		Route::get('allorder-dataTable', [OrderController::class, 'allOrderdataTable'])->name('allorder.dataTable');
		Route::get('variant-dataTable', [ProductController::class, 'varianDataTable'])->name('variant.dataTable');
		Route::get('get-variant-data', [OrderController::class, 'getVariant'])->name('variant.data');
		Route::get('specific-user}', [UserController::class, 'specificUser'])->name('specific.user');
		Route::resource('notification', NotificationController::class);
		//Route::get('admin-seen-notification', [NotificationController::class, 'adminSeenNotification'])->name('adminSeenNoti');
	Route::get('all-notification', [NotificationController::class, 'allNoti'])->name('allNoti');
	Route::get('notification-datatable', [NotificationController::class, 'dataTable'])->name('notification.dataTable');
	//Route::get('get-notification', [NotificationController::class, 'getNotification'])->name('get.notification');
	Route::get('/import-excel', [ExcelImportController::class,'index']);
	Route::post('/import-excel', [ExcelImportController::class,'import'])->name('import.excel');
});
		
         Route::get('test', [HomeController::class, 'test'])->name('test');
         Route::get('shop', [HomeController::class, 'shop'])->name('shop');
		 Route::get('favorite-product', [HomeController::class, 'favoriteProduct'])->name('favorite.product');
         Route::get('offer-product', [HomeController::class, 'offer'])->name('offer');
		 Route::get('contact/{url}', [HomeController::class, 'contactUser'])->name('contact.user');
		 Route::get('check-coupon', [CouponController::class, 'checkCoupon'])->name('cart.checkcoupon');
		 Route::get('delete-coupon', [CouponController::class, 'deleteCoupon'])->name('delete.order.coupon');
		 Route::get('cart', [HomeController::class, 'cart'])->name('cart');
		 Route::get('products/category/{url}', [HomeController::class, 'categoryCat'])->name('catCat');
		 Route::get('faq', [HomeController::class, 'faq'])->name('faq');
		 Route::get('{url}', [HomeController::class,'staticPage'])->name('static');
		 Route::post('subscribe', [HomeController::class, 'subscribe'])->name('subscribe');
		 Route::post('add-cart', [HomeController::class, 'addToCart'])->name('add.cart');
		 Route::get('product/detail/{slu}', [HomeController::class, 'ProductDetail'])->name('detail.product');
		 Route::get('brands/{name}/', [HomeController::class, 'brandProducts'])->name('brand.product');
		 Route::post('/', [HomeController::class,'inquiryVP'])->name('inquiry.product');
		 Route::post('createOrder/order', [HomeController::class, 'createOrder'])->name('createOrder');
		 Route::post('remove/cart', [HomeController::class, 'removeCart'])->name('remove.cart');
		 Route::post('add-favorite', [HomeController::class, 'addFavorite'])->name('add.favorite');
		 
		 Route::post('sendmail', [HomeController::class, 'sendEmail'])->name('sendmail.user');
		Route::post('shipping-charge', [HomeController::class, 'getShiping'])->name('shippingCharge');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Validator;
use Illuminate\Http\Request;

class Brand extends Model
{
     protected $guarded = [];
    public function validator(Request $request, $id = null)
    {
        return Validator::make($request->all(), [
            'name'     => 'required|unique:brands,name,' . ($id ? $id : ''),
            'image'=> 'sometimes|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);
	}
}

app/Http/Controllers/Api/BrandController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\Brand;
use App\Models\Common;
use App\Models\Category;
use App\Models\Faq;
use App\Mail\SendMail;
use Mail;
use App\Models\Query;
use App\Models\Setting;
use App\Models\FavoriteItem;
use App\Models\Order;
use App\Models\Product;
use App\Models\OrderLine;
use Auth;

class BrandController extends Controller
{
	public function brands(){
		$brands = Brand::select('id', 'name', 'image')->get();
		if(!empty($brands))
		{
			return response()->json([
			'message' => 'Fetched successfully',
			'data' => $brands,
		   ],200);
		}else{
			return response()->json([
			'message' => 'Not Found',
			'data' => [],
		   ],404);
		}
	}
	
	public function search(Request $request)
	{
	$catObj= Category::select('id', 'name', 'image')->whereNotNull('parent_id')->where('name', 'LIKE', '%'.$request->searchTxt.'%')->where('status',1)->get();
	$app_maintenance=Setting::getFieldVal('app_maintenance');
	if(!empty($catObj))
		  {
		  return response()->json([
			'message' => 'Fetched successfully',
			'data' => [
			    'categories' => $catObj,
				'app_maintenance' => $app_maintenance,
			],
		   ],200);  
		  }else
		  {
		  return response()->json([
			'message' => 'Not Found',
			'data' => [
			    'categories' => [],
				'app_maintenance' => $app_maintenance,
			],
		   ],404); 
		  }
	}
	
	public function faqs(Request $request){
		$faqs= Faq::where('status', 1)->get();
		if(!empty($faqs))
			  {
			  return response()->json([
				'message' => 'Fetched successfully',
				'data' => $faqs,
			   ],200);  
			  }else
			  {
			  return response()->json([
				'message' => 'Not Found',
				'data' => [],
			   ],404); 
			  }
		}
		
	public function submitQuery(Request $request){
		
		$model= new Query;
		$model->name= $request->name;
		$model->email= $request->email;
		$model->subject= $request->subject;
		$model->message= $request->message;
		$model->status = 0;
		if($model->save()){
        $msg="customer_name=>".$request->name."\n customer_email=".$request->email ."\n subject=".$request->subject ."\n message=".$request->message;
         Common::teligramErrorBot($msg);
		  return response()->json([
				'message' => 'Submitted successfully',
			   ],200); 
		}
        return response()->json([
				'message' => 'Bad Request',
			   ],500); 
		
	}	
	
	public function addFavorite(Request $request)
	{
		$favorite=FavoriteItem::where('user_id',$request->user_id)->where('product_id',$request->proId)->first();
		if(empty($favorite)) 
		{
			$model = new FavoriteItem;
			$model->user_id = $request->user_id;
			$model->product_id = $request->proId;
			$model->save();			
		}else{
			$favorite->delete();
		}
		if(isset($request->type) && $request->type != ""){
		 return	$this->favSpecialproducts($request);
		}
		return $this->favProducts($request);		
	}
	
	public function favProducts($request)
	{
		 $orderId=0;
		 if(isset($request->user_id) && $request->user_id != "" && $request->user_id != null){
          $order=Order::where('user_id',$request->user_id)->where('status',0)->first();
		  if($order){
		  $orderId = $order->id;
		  }
		 }
		 $products = Product::select('id','name','image')->with(['variant','isFavorite'])->where('categeory_id',$request->catId)->where('status',1)->get();
		 $orderLine = OrderLine::select('variant_id','id','qty')->where('order_id',$orderId)->where('status',0)->get()->keyBy('variant_id');
		 $favorite=FavoriteItem::where('user_id',$request->user_id)->count();
		 if(!empty($products))
		 {
			return response()->json([
				'message' => 'Data Fetched',
				'data' =>[
				    'products'=>$products,
				    'orderLine'=>$orderLine,
				    'favCnt'=>$favorite,
				],						
			],200);
		 }else{
			return response()->json([
			'message' => 'Not Found',
			'data' => [],
		   ],404);
		 }		
	}
	
    public function favSpecialproducts($request)
	{
	    $orderId=0;
	    $order=Order::where('user_id',$request->user_id)->where('status',0)->first();
	    if($order){
	     $orderId = $order->id;
	    }
		$productsObj=Product::select('id', 'name', 'image');
		if(isset($request->type) && $request->type == "1") {    //type 1 for whats'new
			$productsObj->orderBy('id', 'DESC')->limit(30);
		}	
		if(isset($request->type) && $request->type == "2") {     // type 2 for popular
			$productsObj->where('best_sell',1);
		}	
		if(isset($request->type) && $request->type == "3") {     // type 3 for product 
			$productsObj->limit(50);
		}		
        if(isset($request->type) && $request->type == "4" && $request->brand_id != "0"){      // type 4 for product by brand 
			$productsObj->where('brand_id',$request->brand_id);
		}	
        if(isset($request->type) && $request->type == "5") {     // type 5 for favoffer 
			return $this->favOffers($request);
		}
        if(isset($request->type) && $request->type == "6") {     // type 6 for only favorite 
			return $this->onlyFavorite();
		}		
		$products=$productsObj->with(['variant','isFavorite'])->where('status',1)->get();
		$orderLine = OrderLine::select('variant_id','id','qty')->where('order_id',$orderId)->where('status',0)->get()->keyBy('variant_id');
		$favorite=FavoriteItem::where('user_id',$request->user_id)->count();
		if(!empty($products))
		{
			return response()->json([
				'message' => 'Data Fetched',
				'data' =>[
				    'products'=>$products,
				    'orderLine'=>$orderLine,
				    'favCnt'=>$favorite,
				],	
			],200);
		}else{
			return response()->json([
			'message' => 'Not Found',
			'data' => [],
		   ],404);
		}
	}
	
	public function favOffers($request){
	    $orderId=0;
	    $order=Order::where('user_id',$request->user_id)->where('status',0)->first();
	    if($order){
	     $orderId = $order->id;
	    }
		 $productIds = Product::getProducts();
		 $products = Product::with(['variant','isFavorite'])->whereHas('variant', function($query) use($productIds){
          $query->whereIn('product_id',$productIds);
         })->whereIn('id',$productIds)->get();
		 $orderLine = OrderLine::select('variant_id','id','qty')->where('order_id',$orderId)->where('status',0)->get()->keyBy('variant_id');
		 $favorite=FavoriteItem::where('user_id',$request->user_id)->count();
		 return response()->json([
				'message' => 'Data Fecthed',
				'data' =>[
				    'products'=>$products,
				    'orderLine'=>$orderLine,
				    'favCnt'=>$favorite,
				],	
			],200);
	}
	
	public function onlyFavorite()
	{
		 $user = Auth::user();
		  $orderId=0;
          $order=Order::where('user_id',$user->id)->where('status',0)->first();
		  if($order){
		  $orderId = $order->id;
		  }
		 $favoriteIds=FavoriteItem::where('user_id',$user->id)->pluck('product_id'); 
		 $products = Product::select('id','name','image')->with(['variant','isFavorite'])->whereIn('id',$favoriteIds)->where('status',1)->get();
		 $orderLine = OrderLine::select('variant_id','id','qty')->where('order_id',$orderId)->where('status',0)->get()->keyBy('variant_id');
		 $favorite=FavoriteItem::where('user_id',$user->id)->count();
		 if(!empty($products))
		 {
			return response()->json([
				'message' => 'Data Fetched',
				'data' =>[
				    'products'=>$products,
				    'orderLine'=>$orderLine,
				    'favCnt'=>$favorite,
				],						
			],200);
		 }else{
			return response()->json([
			'message' => 'Not Found',
			'data' => [],
		   ],404);
		 }		
	}
	
}



 

resources/views/admin/brand/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="tableWrap sectionDash">
            <h1 class="title">Add Brand</h1>
			</div>
			<div class="greyBx">
            <div class="innerWrap">
              {{ Form::open(['route' => 'brand.store','enctype'=>"multipart/form-data","class"=>"themeForm"]) }}

                    {{ csrf_field() }} 
                                      
                    @include('admin.brand.form') 

                {{ Form::close() }}
            

                
   
	</div>
	</div>

@endsection

resources/views/admin/brand/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="tableWrap sectionDash">
            <h1 class="title">Edit Brand</h1>
			</div>
			<div class="greyBx">
            <div class="innerWrap">
              {{ Form::model($model,['route' => ['brand.update', $model->id],'enctype'=>"multipart/form-data"]) }}

                    {{ csrf_field() }}
                    @method('PUT')
                    @include('admin.brand.form')            

                {{ Form::close() }}
           
   </div>
	</div>

@endsection

resources/views/admin/brand/form.blade.php
                  <div class="row">
                    <div class="mb-2rem col-md-6">
                       <label for="" class="form-label">NAME <span class="red">*</span></label>
                      {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control', 'placeholder' => 'Name', 'value' => old('name')]) !!}
					  @if ($errors->has('name'))
						<span class="help-block">
						<strong>{{ $errors->first('name') }}</strong>
						</span>
						@endif
                    </div>
                   <!-- <div class="mb-2rem col-md-6">
                      <label for="" class="form-label">SLUG</label>
                      {!! Form::text('slug', null, ['id' => 'slug', 'class' => 'form-control', 'placeholder' => 'Slug', 'value' => old('slug')]) !!}

			          @if ($errors->has('Slug'))
			          <span class="help-block">
			          <strong>{{ $errors->first('slug') }}</strong>
			          </span>
			          @endif
                    </div>-->
					<div class="mb-2rem col-md-6">
					<label for="" class="form-label">PHOTO</label>
                      {!! Form::file('image', null, ['id' => 'image', 'class' => 'form-control', 'placeholder' => 'Image', 'value' => old('image')]) !!}

			          @if ($errors->has('image'))
			          <span class="help-block">
			          <strong>{{ $errors->first('image') }}</strong>
			          </span>
			          @endif
                    </div>
                    </div>
				        <div class="d-flex justify-content-start">
                        <button type="submit" class="btn btn-primary themeBtn themeFill me-3">Submit</button>
                        <a  href="{{ url()->previous() }}" class="btn btn-primary themeBtn themeUnFill">Cancel</a>
                      </div>

resources/views/admin/brand/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="themeTable">
          <div class="table_id DatatableHeader" >
            <div class="pgTitle">
              <h1>Brands</h1>
            </div>
            <div class="searchBx">
              <input type="text" id="myInputTextField" placeholder="Search">
            </div>
            <div class="tableLength">
              <a href="{{route('brand.create')}}" class="btn btn-primary themeBtn themeFill iconLeft">
                <svg xmlns="http://www.w3.org/2000/svg" width="06" height="06" viewBox="0 0 06 06" fill="none">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 8.69814H6.56325V15.261H8.69814V8.69814H15.261V6.56322H8.69814V0H6.56325V6.56322H0V8.69814Z" fill="white"/>
                </svg>
                &nbsp; Add new</a>
            </div>
          </div>
          
          <div class="table-responsive">
            <table id="listtable1" class="display table table-striped">
			 <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Action</th>					
					
                </tr>
            </thead>
            <tbody>
			@if(count($model)>0)
               @foreach($model as $cat)
               <tr>
			   @if($cat->image != "" || $cat->image != null)
                 <td>@if($cat->image!="")<img src="{{$cat->image}}" width="50px"/>@endif</td>
				@else
					<td class="red">{{"NO Image"}}</td>
				@endif
                 <td>{{ucwords($cat->name)}}</td>
                 
                 <td>{{$cat->slug}}</td>
                <td>
				<div class="d-flex justify-content-start">
                <a  href="{{ route('brand.edit',$cat->id) }}" class="btn me-2 dataActionBtn btnEdit" ><img src="{{asset('img/datatable-edit-plus.svg')}}"/></a> 		 
                <a  onclick="deleteBrand('{{route('brand.destroy',$cat->id) }}')" href="javascript:void(0);" class="btn me-2 dataActionBtn btnDelete"><img src="{{asset('img/datatable-delete.svg')}}"/></a>
                </div> 				
				 </td>
               </tr>
               @endforeach
             @endif
			 </tbody>
            </table>
          </div>
      </div>
@endsection
@push('scripts')
<script type="text/javascript">
$( document ).ready(function() {
   datatableRenderWithoutAjax(1)

} );
function deleteBrand(obj)
{
	$('#confirm-delete .modal-title').html('Delete Brand');
    $('#confirm-delete form').attr('action',obj);
	$('#confirm-delete .text-center').html('Are you sure want to delete this Brand?');
	$('#confirm-delete').modal('show');
}
</script>
@endpush