routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ShippingChargeController;
use App\Http\Controllers\ShippingAreaController;
use App\Http\Controllers\FrontImageController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ExcelImportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

Route::get('/', function () {
    return view('front.wellcome');
});
// routes for mobile application
Route::get('/privacy-policy/app', function () {
	return view('privacy-policy');
});
Route::get('/terms-condition/app', function () {
	return view('termCondition');
});
		Route::post('login', [AuthController::class, 'login'])->name('custom.login');
		Route::post('register', [AuthController::class, 'register'])->name('user.register');
	
	
    Route::get('return-cashfree', [HomeController::class,'returnCashFree'])->name('return.cashefree');
	Route::post('notify-cashfree', [HomeController::class,'notifyPayment'])->name('notify.cashefree');
    Route::get('refresh/captcha', [HomeController::class, 'refreshCaptcha'])->name('refresh.captcha');
    Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');
   // Route::get('self-pickup', [HomeController::class, 'selfPickup'])->name('self.pickup');
    Route::get('time', [ShippingChargeController::class, 'timeCheck'])->name('get.time');
	Route::get('razorpay-create', [HomeController::class,'getRazorpayGateway'])->name('razorpay.payment.get');
    Route::middleware(['auth:sanctum', 'verified'])->group(function (){
	Route::get('dashboard', [HomeController::class, 'mainDashboard'])->name('dashboard');
	Route::get('address-data', [OrderController::class, 'addressData'])->name('address.data');
	Route::post('order-tracking', [OrderController::class, 'orderCreateTracking'])->name('create.order.tracking');
	Route::post('cancel', [OrderController::class, 'CancelOrder'])->name('order.status');
	Route::post('accept', [OrderController::class, 'acceptOrder'])->name('accept.order');
	Route::post('Shipping/vendor', [OrderController::class, 'shippingUpdate'])->name('shipping.update');
	Route::post('Shipping-address-update', [OrderController::class, 'shippingStatusUpdate'])->name('shipping-address-update');
	Route::get('/find-user/{id}/', [UserController::class, 'userName']);
	Route::resource('address', AddressController::class);
	//Route::get('address-edit', [AddressController::class, 'addressEdit'])->name('address.edit');
	Route::post('new-address-store', [AddressController::class, 'addressAdd'])->name('new.address.store');
	Route::get('user/edit/address/{id}', [AddressController::class, 'Editaddress'])->name('editadr');
	Route::get('user/delete/address/{id}', [AddressController::class, 'DeleteAddress'])->name('deleteadr');
	Route::post('add-delete', [HomeController::class, 'addDelete'])->name('add.delete');
     
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('order-item-{id}', [HomeController::class,'viewItems'])->name('views.items');
	Route::get('my-order/list', [OrderController::class, 'userOderList'])->name('user.order.list');
	Route::get('myprofile', [UserController::class, 'MyProfile'])->name('myprofile.index');
});
Route::middleware('admin')->group(function (){
		Route::get('export-product', [HomeController::class, 'exportProduct'])->name('export.product');
		Route::put('selfprofile/{id}', [HomeController::class, 'selfProfile'])->name('self.update');
	    Route::post('file-uplaod', [HomeController::class, 'uplaodFile'])->name('file.upload');
	    Route::delete('queries-destroy{id}', [HomeController::class, 'queryDestroy'])->name('query.destroy');
	    Route::get('update-status{id}', [HomeController::class, 'updateStatus'])->name('status.update.query');
	    
	    Route::get('query', [HomeController::class, 'queryIndex'])->name('query.index');
		Route::resource('area', ShippingAreaController::class);
		Route::resource('faqs', FaqController::class);
		Route::resource('frontimage', FrontImageController::class);
		Route::resource('charge', ShippingChargeController::class);
		Route::resource('user', UserController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('faqs.dataTable', [FaqController::class, 'faqdataTable'])->name('faqs.dataTable');
		Route::resource('brand', BrandController::class);
		Route::resource('category', CategoryController::class);
		Route::get('cat.dataTable', [CategoryController::class, 'dataTable'])->name('cat.dataTable');
		Route::resource('blog', BlogController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('blog-datatable', [BlogController::class, 'dataTable'])->name('blog.dataTable');
		Route::resource('product', ProductController::class);
		Route::get('product.dataTable', [ProductController::class, 'dataTable'])->name('product.dataTable');
		Route::get('get-variant', [ProductController::class, 'variantData'])->name('variant.get.data');
		Route::resource('settings', SettingsController::class);
		Route::post('settings/update', [SettingsController::class, 'update'])->name('setting.update');
		Route::resource('order', OrderController::class);
		Route::get('/product-variant/{pvt}/', [OrderController::class, 'variantName']);
		Route::resource('page', PageController::class);    
		Route::get('page-datatable', [PageController::class,'dataTable'])->name('page.dataTable');
		Route::post('images-file/{foldername}', [PageController::class,'uploadImages'])->name('page.imageupload');
		Route::get('variant.found', [OrderController::class, 'variantFound'])->name('variant.found');
        Route::get('order-invoice/{id}', [OrderController::class, 'orderinvoice'])->name('order.invoice');
		Route::get('order-dataTable', [OrderController::class, 'dataTable'])->name('order.dataTable');
		Route::get('allorder-dataTable', [OrderController::class, 'allOrderdataTable'])->name('allorder.dataTable');
		Route::get('variant-dataTable', [ProductController::class, 'varianDataTable'])->name('variant.dataTable');
		Route::get('get-variant-data', [OrderController::class, 'getVariant'])->name('variant.data');
		Route::get('specific-user}', [UserController::class, 'specificUser'])->name('specific.user');
		Route::resource('notification', NotificationController::class);
		//Route::get('admin-seen-notification', [NotificationController::class, 'adminSeenNotification'])->name('adminSeenNoti');
	Route::get('all-notification', [NotificationController::class, 'allNoti'])->name('allNoti');
	Route::get('notification-datatable', [NotificationController::class, 'dataTable'])->name('notification.dataTable');
	//Route::get('get-notification', [NotificationController::class, 'getNotification'])->name('get.notification');
	Route::get('/import-excel', [ExcelImportController::class,'index']);
	Route::post('/import-excel', [ExcelImportController::class,'import'])->name('import.excel');
});
		
         Route::get('test', [HomeController::class, 'test'])->name('test');
         Route::get('shop', [HomeController::class, 'shop'])->name('shop');
		 Route::get('favorite-product', [HomeController::class, 'favoriteProduct'])->name('favorite.product');
         Route::get('offer-product', [HomeController::class, 'offer'])->name('offer');
		 Route::get('contact/{url}', [HomeController::class, 'contactUser'])->name('contact.user');
		 Route::get('check-coupon', [CouponController::class, 'checkCoupon'])->name('cart.checkcoupon');
		 Route::get('delete-coupon', [CouponController::class, 'deleteCoupon'])->name('delete.order.coupon');
		 Route::get('cart', [HomeController::class, 'cart'])->name('cart');
		 Route::get('products/category/{url}', [HomeController::class, 'categoryCat'])->name('catCat');
		 Route::get('faq', [HomeController::class, 'faq'])->name('faq');
		 Route::get('{url}', [HomeController::class,'staticPage'])->name('static');
		 Route::post('subscribe', [HomeController::class, 'subscribe'])->name('subscribe');
		 Route::post('add-cart', [HomeController::class, 'addToCart'])->name('add.cart');
		 Route::get('product/detail/{slu}', [HomeController::class, 'ProductDetail'])->name('detail.product');
		 Route::get('brands/{name}/', [HomeController::class, 'brandProducts'])->name('brand.product');
		 Route::post('/', [HomeController::class,'inquiryVP'])->name('inquiry.product');
		 Route::post('createOrder/order', [HomeController::class, 'createOrder'])->name('createOrder');
		 Route::post('remove/cart', [HomeController::class, 'removeCart'])->name('remove.cart');
		 Route::post('add-favorite', [HomeController::class, 'addFavorite'])->name('add.favorite');
		 
		 Route::post('sendmail', [HomeController::class, 'sendEmail'])->name('sendmail.user');
		Route::post('shipping-charge', [HomeController::class, 'getShiping'])->name('shippingCharge');

resources/views/admin/area/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="tableWrap sectionDash">
            <h1 class="title">Add Area</h1>
			</div>
			<div class="greyBx">
            <div class="innerWrap">
              {{ Form::open(['route' => 'area.store','enctype'=>"multipart/form-data","class"=>"themeForm"]) }}

                    {{ csrf_field() }} 
                                      
                    @include('admin.area.form') 

                {{ Form::close() }}
            

                
   
	</div>
	</div>

@endsection

resources/views/admin/area/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="tableWrap sectionDash">
            <h1 class="title">Edit Area</h1>
			</div>
			<div class="greyBx">
            <div class="innerWrap">
              {{ Form::model($model,['route' => ['area.update', $model->id],'enctype'=>"multipart/form-data"]) }}
                    {{ csrf_field() }}
                    @method('PUT')
                    @include('admin.area.form')            

                {{ Form::close() }}
           
   </div>
	</div>

@endsection

resources/views/admin/area/form.blade.php
                  <div class="row">
                    <div class="mb-2rem col-md-6">
                       <label for="" class="form-label">Area <span class="red">*</span></label>
                      {!! Form::text('area', null, ['id' =>'area', 'class' => 'form-control', 'placeholder' => 'Area Name', 'value' => old('area')]) !!}
					  @if ($errors->has('area'))
						<span class="help-block">
						<strong>{{ $errors->first('area') }}</strong>
						</span>
						@endif
                    </div>
                    <div class="mb-2rem col-md-6">
                      <label for="" class="form-label">Charge Amount</label>
                      {!! Form::text('charge', null, ['id' => 'charge', 'class' => 'form-control', 'placeholder' => 'Amount', 'value' => old('charge')]) !!}

			          @if ($errors->has('charge'))
			          <span class="help-block">
			          <strong>{{ $errors->first('charge') }}</strong>
			          </span>
			          @endif
                    </div>
                    </div>
					 <div class="row">
                    <div class="mb-2rem col-md-6">
                       <label for="" class="form-label">Start Time AM/PM</label>
                      {!! Form::text('start_time', null, ['id' =>'start_time', 'class' => 'form-control', 'placeholder' => 'Start Time', 'value' => old('start_time')]) !!}
					  @if ($errors->has('start_time'))
						<span class="help-block">
						<strong>{{ $errors->first('start_time') }}</strong>
						</span>
						@endif
                    </div>
                    <div class="mb-2rem col-md-6">
                      <label for="" class="form-label">End Time AM/PM</label>
                      {!! Form::text('end_time', null, ['id' => 'end_time', 'class' => 'form-control', 'placeholder' => 'Amount', 'value' => old('end_time')]) !!}

			          @if ($errors->has('end_time'))
			          <span class="help-block">
			          <strong>{{ $errors->first('end_time') }}</strong>
			          </span>
			          @endif
                    </div>
                    </div>
					<div class="row">
                    <div class="mb-2rem col-md-6">
					<label for="status" class="form-label">Status</label>
			 {{ Form::select('status', ['1'=>'Active','0'=>'InActive'],null, ['class' => 'form-select', 'value' => old('status')]) }}
			@if ($errors->has('status'))
				<span class="help-block">
					<strong>{{ $errors->first('status') }}</strong>
				</span>
			@endif
                       
                    </div>
                   
                    </div>
				        <div class="d-flex justify-content-start">
                        <button type="submit" class="btn btn-primary themeBtn themeFill me-3">Submit</button>
                        <a  href="{{ url()->previous() }}" class="btn btn-primary themeBtn themeUnFill">Cancel</a>
                      </div>

resources/views/admin/area/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="themeTable">
          <div class="table_id DatatableHeader" >
            <div class="pgTitle">
              <h1>Shipping Area</h1>
            </div>
            <div class="searchBx">
              <input type="text" id="myInputTextField" placeholder="Search">
            </div>
            <div class="tableLength">
              <a href="{{route('area.create')}}" class="btn btn-primary themeBtn themeFill iconLeft">
                <svg xmlns="http://www.w3.org/2000/svg" width="06" height="06" viewBox="0 0 06 06" fill="none">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 8.69814H6.56325V15.261H8.69814V8.69814H15.261V6.56322H8.69814V0H6.56325V6.56322H0V8.69814Z" fill="white"/>
                </svg>
                &nbsp; Add new</a>
            </div>
          </div>
          
          <div class="table-responsive">
            <table id="listtable1" class="display table table-striped">
			 <thead>
                <tr>
                    <th>Shipping Area</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Shipping Charge</th>
					<th>Status</th>
                    <th>Action</th>					
					
                </tr>
            </thead>
            <tbody>
			@if(count($model)>0)
               @foreach($model as $ar)
               <tr>
                 <td>{{$ar->area}}</td>
				 <td>{{$ar->start_time}}</td>
				 <td>{{$ar->end_time}}</td>
				 <td>{{$ar->charge}}</td>
				 <td>{{$ar->status}}</td>
                <td>
				<div class="d-flex justify-content-start">
                <a  href="{{ route('area.edit',$ar->id) }}" class="btn me-2 dataActionBtn btnEdit" ><img src="{{asset('img/datatable-edit-plus.svg')}}"/></a> 		 
                <a  onclick="deleteArea('{{route('area.destroy',$ar->id) }}')" href="javascript:void(0);" class="btn me-2 dataActionBtn btnDelete"><img src="{{asset('img/datatable-delete.svg')}}"/></a>
                </div> 				
				 </td>
               </tr>
               @endforeach
             @endif
			 </tbody>
            </table>
          </div>
      </div>
@endsection
@push('scripts')
<script type="text/javascript">
$( document ).ready(function() {
   datatableRenderWithoutAjax(1)

} );
function deleteArea(obj)
{
	$('#confirm-delete .modal-title').html('Delete Area');
    $('#confirm-delete form').attr('action',obj);
	$('#confirm-delete .text-center').html('Are you sure want to delete this Area?');
	$('#confirm-delete').modal('show');
}
</script>
@endpush