routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ShippingChargeController;
use App\Http\Controllers\ShippingAreaController;
use App\Http\Controllers\FrontImageController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ExcelImportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

Route::get('/', function () {
    return view('front.wellcome');
});
// routes for mobile application
Route::get('/privacy-policy/app', function () {
	return view('privacy-policy');
});
Route::get('/terms-condition/app', function () {
	return view('termCondition');
});
		Route::post('login', [AuthController::class, 'login'])->name('custom.login');
		Route::post('register', [AuthController::class, 'register'])->name('user.register');
	
	
    Route::get('return-cashfree', [HomeController::class,'returnCashFree'])->name('return.cashefree');
	Route::post('notify-cashfree', [HomeController::class,'notifyPayment'])->name('notify.cashefree');
    Route::get('refresh/captcha', [HomeController::class, 'refreshCaptcha'])->name('refresh.captcha');
    Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');
   // Route::get('self-pickup', [HomeController::class, 'selfPickup'])->name('self.pickup');
    Route::get('time', [ShippingChargeController::class, 'timeCheck'])->name('get.time');
	Route::get('razorpay-create', [HomeController::class,'getRazorpayGateway'])->name('razorpay.payment.get');
    Route::middleware(['auth:sanctum', 'verified'])->group(function (){
	Route::get('dashboard', [HomeController::class, 'mainDashboard'])->name('dashboard');
	Route::get('address-data', [OrderController::class, 'addressData'])->name('address.data');
	Route::post('order-tracking', [OrderController::class, 'orderCreateTracking'])->name('create.order.tracking');
	Route::post('cancel', [OrderController::class, 'CancelOrder'])->name('order.status');
	Route::post('accept', [OrderController::class, 'acceptOrder'])->name('accept.order');
	Route::post('Shipping/vendor', [OrderController::class, 'shippingUpdate'])->name('shipping.update');
	Route::post('Shipping-address-update', [OrderController::class, 'shippingStatusUpdate'])->name('shipping-address-update');
	Route::get('/find-user/{id}/', [UserController::class, 'userName']);
	Route::resource('address', AddressController::class);
	//Route::get('address-edit', [AddressController::class, 'addressEdit'])->name('address.edit');
	Route::post('new-address-store', [AddressController::class, 'addressAdd'])->name('new.address.store');
	Route::get('user/edit/address/{id}', [AddressController::class, 'Editaddress'])->name('editadr');
	Route::get('user/delete/address/{id}', [AddressController::class, 'DeleteAddress'])->name('deleteadr');
	Route::post('add-delete', [HomeController::class, 'addDelete'])->name('add.delete');
     
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('order-item-{id}', [HomeController::class,'viewItems'])->name('views.items');
	Route::get('my-order/list', [OrderController::class, 'userOderList'])->name('user.order.list');
	Route::get('myprofile', [UserController::class, 'MyProfile'])->name('myprofile.index');
});
Route::middleware('admin')->group(function (){
		Route::get('export-product', [HomeController::class, 'exportProduct'])->name('export.product');
		Route::put('selfprofile/{id}', [HomeController::class, 'selfProfile'])->name('self.update');
	    Route::post('file-uplaod', [HomeController::class, 'uplaodFile'])->name('file.upload');
	    Route::delete('queries-destroy{id}', [HomeController::class, 'queryDestroy'])->name('query.destroy');
	    Route::get('update-status{id}', [HomeController::class, 'updateStatus'])->name('status.update.query');
	    
	    Route::get('query', [HomeController::class, 'queryIndex'])->name('query.index');
		Route::resource('area', ShippingAreaController::class);
		Route::resource('faqs', FaqController::class);
		Route::resource('frontimage', FrontImageController::class);
		Route::resource('charge', ShippingChargeController::class);
		Route::resource('user', UserController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('faqs.dataTable', [FaqController::class, 'faqdataTable'])->name('faqs.dataTable');
		Route::resource('brand', BrandController::class);
		Route::resource('category', CategoryController::class);
		Route::get('cat.dataTable', [CategoryController::class, 'dataTable'])->name('cat.dataTable');
		Route::resource('blog', BlogController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('blog-datatable', [BlogController::class, 'dataTable'])->name('blog.dataTable');
		Route::resource('product', ProductController::class);
		Route::get('product.dataTable', [ProductController::class, 'dataTable'])->name('product.dataTable');
		Route::get('get-variant', [ProductController::class, 'variantData'])->name('variant.get.data');
		Route::resource('settings', SettingsController::class);
		Route::post('settings/update', [SettingsController::class, 'update'])->name('setting.update');
		Route::resource('order', OrderController::class);
		Route::get('/product-variant/{pvt}/', [OrderController::class, 'variantName']);
		Route::resource('page', PageController::class);    
		Route::get('page-datatable', [PageController::class,'dataTable'])->name('page.dataTable');
		Route::post('images-file/{foldername}', [PageController::class,'uploadImages'])->name('page.imageupload');
		Route::get('variant.found', [OrderController::class, 'variantFound'])->name('variant.found');
        Route::get('order-invoice/{id}', [OrderController::class, 'orderinvoice'])->name('order.invoice');
		Route::get('order-dataTable', [OrderController::class, 'dataTable'])->name('order.dataTable');
		Route::get('allorder-dataTable', [OrderController::class, 'allOrderdataTable'])->name('allorder.dataTable');
		Route::get('variant-dataTable', [ProductController::class, 'varianDataTable'])->name('variant.dataTable');
		Route::get('get-variant-data', [OrderController::class, 'getVariant'])->name('variant.data');
		Route::get('specific-user}', [UserController::class, 'specificUser'])->name('specific.user');
		Route::resource('notification', NotificationController::class);
		//Route::get('admin-seen-notification', [NotificationController::class, 'adminSeenNotification'])->name('adminSeenNoti');
	Route::get('all-notification', [NotificationController::class, 'allNoti'])->name('allNoti');
	Route::get('notification-datatable', [NotificationController::class, 'dataTable'])->name('notification.dataTable');
	//Route::get('get-notification', [NotificationController::class, 'getNotification'])->name('get.notification');
	Route::get('/import-excel', [ExcelImportController::class,'index']);
	Route::post('/import-excel', [ExcelImportController::class,'import'])->name('import.excel');
});
		
         Route::get('test', [HomeController::class, 'test'])->name('test');
         Route::get('shop', [HomeController::class, 'shop'])->name('shop');
		 Route::get('favorite-product', [HomeController::class, 'favoriteProduct'])->name('favorite.product');
         Route::get('offer-product', [HomeController::class, 'offer'])->name('offer');
		 Route::get('contact/{url}', [HomeController::class, 'contactUser'])->name('contact.user');
		 Route::get('check-coupon', [CouponController::class, 'checkCoupon'])->name('cart.checkcoupon');
		 Route::get('delete-coupon', [CouponController::class, 'deleteCoupon'])->name('delete.order.coupon');
		 Route::get('cart', [HomeController::class, 'cart'])->name('cart');
		 Route::get('products/category/{url}', [HomeController::class, 'categoryCat'])->name('catCat');
		 Route::get('faq', [HomeController::class, 'faq'])->name('faq');
		 Route::get('{url}', [HomeController::class,'staticPage'])->name('static');
		 Route::post('subscribe', [HomeController::class, 'subscribe'])->name('subscribe');
		 Route::post('add-cart', [HomeController::class, 'addToCart'])->name('add.cart');
		 Route::get('product/detail/{slu}', [HomeController::class, 'ProductDetail'])->name('detail.product');
		 Route::get('brands/{name}/', [HomeController::class, 'brandProducts'])->name('brand.product');
		 Route::post('/', [HomeController::class,'inquiryVP'])->name('inquiry.product');
		 Route::post('createOrder/order', [HomeController::class, 'createOrder'])->name('createOrder');
		 Route::post('remove/cart', [HomeController::class, 'removeCart'])->name('remove.cart');
		 Route::post('add-favorite', [HomeController::class, 'addFavorite'])->name('add.favorite');
		 
		 Route::post('sendmail', [HomeController::class, 'sendEmail'])->name('sendmail.user');
		Route::post('shipping-charge', [HomeController::class, 'getShiping'])->name('shippingCharge');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Product;
use App\Models\State;
use Illuminate\Http\Request;
use Auth;
use App\Models\Address;
use App\Models\ShippingCharge;
use App\Models\ShippingArea;
use Validator;

class Order extends Model
{
    use HasFactory;
	protected $fillable = ['status','delivery_date'];
	public function validatorAddOrder(Request $request)
	{
		return Validator::make($request->all(),[
			'user_id'=> 'required'
		]);
	}
	 public function userOrderUpdate(Request $request, $id = null)
    {
        return Validator::make($request->all(), [
			'user_id'     => 'required',
		]);
	}
	public function validator(Request $request)
    {
		$isAddressSection=true;
		if(Auth::check())
		{
			$user=Auth::user();
			if(count($user->userAddress)>0)
			{
				$isAddressSection=false;
			}
			
		}
		if($isAddressSection)
		{
			 $models = new Address;
			 $validator = $models->validator($request);
			 return $validator;
		}
		else{
			return Validator::make($request->all(), [
            'address_id'     => 'required'            
          ]);
		}
       
		
	}
    public function order()
	{
		return $this->hasOne(OrderLine::class, 'order_id','id');
	} 	
	public function customer()
	{
		return $this->hasOne(User::class, 'id','customer_id');
	} 
	public function shippingAddress()
	{
		return $this->hasOne(Address::class, 'id','address_id');
	} 
	public function state()
	{
		return $this->hasOne(State::class, 'id','state_id');
	} 
	public function user()
	{
		return $this->hasOne(User::class, 'id','user_id');
	} 
	 
	public function orderData($oid)
	{
		$order=Order::find($oid);
		return $order;
	}
	
	public function product()
	{
		return $this->hasOne(Product::class, 'id','product_id');
	}
	public function getOrderLines()
	{ 
		return $this->hasMany(OrderLine::class, 'order_id','id');
	}
	public function reCalculateFee(){
		$orderLines=$this->getOrderLines;
		if(count($orderLines)>0)
		{
			$orderAmt=$orderLines->sum('amount');
			$this->gst_amount=$orderLines->sum('gst_amount');
			$this->total_amount=$orderAmt;
			$this->order_amount=$orderAmt;
			$this->save();
		}
	}
	public function area()
	{
		return $this->hasMany(ShippingArea::class, 'id','area_id');
	}
	public function addressArea()
	{
		return $this->hasOne(ShippingArea::class, 'id','area_id');
	}
	public function shippingCharge()
	{
		return $this->hasMany(ShippingCharge::class, 'id','shipping_charge_id');
	}
	public static function getUserOrders($createNewOrder)
	{
		$currentDecivceId = request()->cookie('device_id');
		$user_id=0;
		if(Auth::check())
		{
			$user_id=Auth::user()->id;	
		}
			
		if($currentDecivceId=="" || $currentDecivceId==null || $currentDecivceId=="null")
		{
			$currentDecivceId=md5(time());					
		}
		$order=new self;
		$order=self::Where('status','=',0)->where('device_id',$currentDecivceId)->first();
		if(empty($order) && $user_id>0 )
		{
			$order=self::Where('status','=',0)->where('user_id',$user_id)->first();
		}
		if(!empty($order) && $user_id>0)
		{			
			$order->user_id=$user_id;
			$order->save();			
		}
		if(empty($order) && $createNewOrder)
		{
			$order=new self;
			$order->user_id=$user_id;
			$order->status=0;
			$order->device_id=$currentDecivceId;
			$order->save();			
		}
		return $order;
	}
	public function ManyProduct($id)
	{ 
			$product= OrderLine::where('order_id',$id)->get();
			
				return $product;
			
	}
	public function getStatus($id){
		$order_list=Order::find($id);
		$status="";
		if($order_list->status==1){
			$status=" Pending";
		}
		else if($order_list->status==2){
			$status=" Out of Delivere";
		}
		else if($order_list->status==3){
			$status="Delivered";
		}
		else if($order_list->status==4){
			$status="Cancelled";
		}
		return $status;
	}
	public function Address()
	{
		return $this->hasOne(Address::class, 'user_id','user_id');
	} 
}

resources/views/admin/orders/order-list.blade.php
@extends('layouts.admin')
@section('content')
<?php
use App\Models\User;
$user=Auth::user();
?>
	<div class="tab" style="margin-top: -55px;">
	  <button class="tablinks"id="orderdetailBoutton" onclick="orderDetail('todayOrder')">Today Order</button>
	<button class="tablinks" id="reportBoutton"onclick="orderDetail('allOrder')">All Order</button>
	<div class="pull-right">
			<a class="btn btn-primary themeBtn themeFill iconLeft"  style="margin-right:10px;margin-top: 4px;" href="{{route('order.create')}}">Add Orders</a>
</div>
		
	</div>
	<div id="todayOrder" class="themeTable">
          <div class="table_id DatatableHeader" >
            
                    </div>
          
          <div class="table-responsive">
            <table id="listtable1" class="display table table-striped">
			 <thead>
                <tr>
                    <th>Order#</th>
                    <th>Product Name</th> 
                    <th>Customer</th> 
                    <th>Shiping Address</th> 
                    <th>Payment Status</th> 
                    <th>Payment Method</th> 
                    <th>Payment Order Id</th> 
                    <th>Order Status</th>              
                    <th>Order Amount</th>                 
                    <th>Created At</th>                 
                    <th>Updated At</th>              
                    <th>Action</th>    
                </tr>
            </thead>
            <tbody>
			 </tbody>
            </table>
          </div>
      </div>
		<div id="allOrder" class="themeTable">
          <div class="table_id DatatableHeader" >
                      <div class="col-md-2" style="margin-top: 27px;margin-left: 10px;">
                        <input id="all_start_date" class="form-control" placeholder="Select Start Date" name="start_date" type="text">
                      </div>
					  &nbsp;
                      <div class="col-md-2" style="margin-top: 27px;margin-left: 25px;">
                         <input id="all_end_date" class="form-control" placeholder="Select End Date" name="end_date" type="text">
                      </div>
					  &nbsp;
                      <div class="col-md-1" style="margin-left: 15px;margin-top: 27px;">
                      <a href="javascript:void(0);" class="btn btn-primary themeBtn btnGrey " onclick="filterData()">Filter</a>
                     </div>
					 &nbsp;
					<!-- <div class="col-md-1" style="margin-left: 50px;margin-top: 27px;">
                      <a href="javascript:void(0);" class="btn btn-primary themeBtn themeFill iconLeft" onclick="exportOrder()">Export</a>
                    </div>-->
                    </div>
          
          <div class="table-responsive">
            <table id="listtable2" class="display table table-striped">
			 <thead>
                <tr>
                    <th>Order#</th>
                    <th>Product Name</th> 
                    <th>Customer</th> 
                    <th>Shiiping Address</th> 
                    <th>Status</th>                 
                    <th>Order Amount</th>                 
                    <th>Created At</th>                 
                    <th>Updated At</th>                 
                    <th>Action</th>    
                </tr>
            </thead>
            <tbody>
			 </tbody>
            </table>
          </div>
      </div>

@endsection
@push('modals')
@include('admin.orders.status-update-pop-up')
@endpush
@push('scripts')
<script type="text/javascript">
	$( document ).ready(function() {
	dataTable=$('#listtable1').DataTable({
			responsive: true,
			processing: true,
			serverSide: true,
			searching: false,
			ajax:  {
				"url":"{{route('order.dataTable')}}",
				"data": function(data){
				}
			},
			stateSave: true,
			 bLengthChange: true,
			bInfo: false,

		});
		dataTable=$('#listtable2').DataTable({
			responsive: true,
			processing: true,
			serverSide: true,
			searching: false,
			ajax:  {
				"url":"{{route('allorder.dataTable')}}",
				"data": function(data){
					data.start_date = $('#all_start_date').val();
          data.end_date = $('#all_end_date').val();
				}
			},
			stateSave: true,
			 bLengthChange: true,
			bInfo: false,

		});
		$( "#all_start_date" ).datepicker({ dateFormat: 'yy-mm-dd' }).val();
		$( "#all_end_date" ).datepicker({ dateFormat: 'yy-mm-dd' }).val();
	orderDetail('todayOrder');
	});

  function updateStatus(oid){
 
            $('#update_Order_id').val(oid);
           $('#status-pop-up').modal('show');
  }
 function filterData()
{
	dataTable.draw();
}
function orderDetail(oderId) {
	var odrderO= oderId;
	if(odrderO=="allOrder"){
		$('#allOrder').show();
		$('#reportBoutton').addClass('active');
		$('#todayOrder').hide();
		$('#orderdetailBoutton').removeClass('active');
	}
	if(odrderO=="todayOrder"){
		$('#allOrder').hide();
		$('#reportBoutton').removeClass('active');
		$('#orderdetailBoutton').addClass('active');
		$('#todayOrder').show();
	}
}
</script>
@endpush

resources/views/admin/orders/pop.blade.php
<div class="modal fade themeModal"  id="shipping-pop-up"  tabindex="-1" aria-labelledby="deleteConfirmLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header justify-content-center">
        <h5 class="modal-title" id="deleteConfirmLabel">Shipping</h5>
        <button type="button" class="btn-close d-none" data-f-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pt-1 pb-2">
        <p class="msg-o mb-0 text-center"></p>
		  <form action="" id="popform">
	   <?php
$userRole=config('constant.userRole');
?>
  <div class="row">
	 <div class="col-md-12">
	  <div class="row">
	  <h4>Shipping Detail</h4>
	  
	  
		<div class="mb-3 col-md-6 {{ $errors->has('height') ? 'has-error' : '' }}">
		
		   {{ Form::text('height',  null, ['class' => 'form-control','placeholder'=>'height','id'=>'height']) }}
			@if ($errors->has('height'))
				<span class="help-block">
					<strong>{{ $errors->first('height') }}</strong>
				</span>
			@endif
		</div>
	    <div class="mb-3 col-md-6 {{ $errors->has('width') ? 'has-error' : '' }}">
		 
			 {{ Form::text('width',null, ['class' => 'form-control','id'=>'width','placeholder'=>'width']) }}
			@if ($errors->has('width'))
				<span class="help-block">
					<strong>{{ $errors->first('width') }}</strong>
				</span>
			@endif
		</div>
        
		<div class="mb-3 col-md-6 {{ $errors->has('length') ? 'has-error' : '' }}">
		 
			 {{ Form::text('length',null, ['class' => 'form-control','id'=>'length','placeholder'=>'Length']) }}
			@if ($errors->has('length'))
				<span class="help-block">
					<strong>{{ $errors->first('length') }}</strong>
				</span>
			@endif
		</div>	
		<div class="mb-3 col-md-6 {{ $errors->has('breath') ? 'has-error' : '' }}">
		 
			 {{ Form::text('breath',null, ['class' => 'form-control','id'=>'breath','placeholder'=>'Breath']) }}
			@if ($errors->has('breath'))
				<span class="help-block">
					<strong>{{ $errors->first('breath') }}</strong>
				</span>
			@endif
		</div>		
		</div>
	 </div>


	 <div class="col-md-12">
	  <div class="row">
	  <h4>Vendor Address</h4>
	  
	  
		<div class="mb-3 col-md-6 {{ $errors->has('first_name') ? 'has-error' : '' }}">
		  
		   {{ Form::text('first_name',  null, ['class' => 'form-control','placeholder'=>'First Name','id'=>'first_name','required'=>'required']) }}
			@if ($errors->has('first_name'))
				<span class="help-block">
					<strong>{{ $errors->first('first_name') }}</strong>
				</span>
			@endif
		</div><div class="mb-3 col-md-6 {{ $errors->has('last_name') ? 'has-error' : '' }}">
		  
		   {{ Form::text('last_name',  null, ['class' => 'form-control','placeholder'=>'Last Name','id'=>'last_name','required'=>'required']) }}
			@if ($errors->has('last_name'))
				<span class="help-block">
					<strong>{{ $errors->first('last_name') }}</strong>
				</span>
			@endif
		</div><div class="mb-3 col-md-6 {{ $errors->has('email_id') ? 'has-error' : '' }}">
		  
		   {{ Form::text('email_id',  null, ['class' => 'form-control','placeholder'=>'Email Id','id'=>'email_id','required'=>'required']) }}
			@if ($errors->has('email_id'))
				<span class="help-block">
					<strong>{{ $errors->first('email_id') }}</strong>
				</span>
			@endif
		</div>
<div class="mb-3 col-md-6 {{ $errors->has('phone_no') ? 'has-error' : '' }}">
		 
			 {{ Form::text('phone_no',null, ['class' => 'form-control','id'=>'phone_no','placeholder'=>'phone','required'=>'required']) }}
			@if ($errors->has('phone_no'))
				<span class="help-block">
					<strong>{{ $errors->first('phone_no') }}</strong>
				</span>
			@endif
		</div>		
<div class="mb-3 col-md-6 {{ $errors->has('address_1') ? 'has-error' : '' }}">
		  
		   {{ Form::text('address_1',  null, ['class' => 'form-control','placeholder'=>'address 1','id'=>'address_1','required'=>'required']) }}
			@if ($errors->has('address_1'))
				<span class="help-block">
					<strong>{{ $errors->first('address_1') }}</strong>
				</span>
			@endif
		</div>
	    <div class="mb-3 col-md-6 {{ $errors->has('address_2') ? 'has-error' : '' }}">
		
			 {{ Form::text('address_2',null, ['class' => 'form-control','id'=>'address_2','placeholder'=>'address 2']) }}
			@if ($errors->has('address_2'))
				<span class="help-block">
					<strong>{{ $errors->first('address_2') }}</strong>
				</span>
			@endif
		</div>
        <div class="mb-3 col-md-6 {{ $errors->has('city') ? 'has-error' : '' }}">
		 
			 {{ Form::text('city',null, ['class' => 'form-control','id'=>'city','placeholder'=>'city','required'=>'required']) }}
			@if ($errors->has('city'))
				<span class="help-block">
					<strong>{{ $errors->first('city') }}</strong>
				</span>
			@endif
		</div>	
 <div class="mb-3 col-md-6 {{ $errors->has('state') ? 'has-error' : '' }}">
		 
			 {{ Form::text('state_id',null, ['class' => 'form-control','id'=>'state_id','placeholder'=>'state','required'=>'required']) }}
			@if ($errors->has('state_id'))
				<span class="help-block">
					<strong>{{ $errors->first('state') }}</strong>
				</span>
			@endif
		</div>	
 <div class="mb-3 col-md-6 {{ $errors->has('zipcode') ? 'has-error' : '' }}">
		 
			 {{ Form::text('zipcode',null, ['class' => 'form-control','id'=>'zipcode','placeholder'=>'zipcode','required'=>'required']) }}
			@if ($errors->has('zipcode'))
				<span class="help-block">
					<strong>{{ $errors->first('zipcode') }}</strong>
				</span>
			@endif
		</div>	

		</div>
	 </div>
	 </div>
	 <div class="d-flex justify-content-start ">
	 <button type="button" class="btn btn-primary themeBtn themeFill me-3" onclick="submitData(this)" id="submit_button">Submit</button>
	
		 <button type="button" class="btn btn-primary themeBtn themeUnFill me-3" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
		 <input type="hidden" name="formType" value="3" />
		<input type="hidden" name="product_id" value="" id="product_id"/>
		<input type="hidden" name="order_id" value="" id="order_id" />
		<input type="hidden" name="vendor_id" value="" id="vendor_id" />
		<!--<input type="hidden" name="phone_no" value="" id="phone_no" />-->
</div> 
   
 </form>
      </div>
      <div class="modal-footer justify-content-center pt-0">
	 
	<!--<div class="d-flex justify-content-start ">
	  <button type="submit" class="btn btn-primary themeBtn themeFill me-3">Submit</button>
	  <a href="{{route('user.index')}}" class="btn btn-primary themeBtn themeUnFill me-3">Cancel</a>
	</div> -->
 
        
		
      </div>
    </div>
  </div>
</div>
@push('scripts')
<script type="text/javascript">
function submitData(obj){
		var first_name=$('#first_name').val();
		var last_name=$('#last_name').val();
		var email_id= $('#email_id').val();
		var address_1= $('#address_1').val();
		var address_2= $('#address_2').val();
		var city= $('#city').val();
		var state_id= $('#state_id').val();
		var zipcode= $('#zipcode').val();
		var phone_no= $('#phone_no').val();
		var height= $('#height').val();
		var width= $('#width').val();
		var product_length= $('#length').val();
		var breath= $('#breath').val();
		var order_id= $('#order_id').val();
		var vendor_id= $('#vendor_id').val();
		if(first_name==" " || last_name=="" || email_id=="" || address_1=="" || address_2=="" || city=="" || zipcode=="" || phone_no=="")
		{
				toastr.error('Please Provide all details of user.');
			  return false;
		}
		if(height=="" || width=="" || product_length=="" || breath=="")
		{
				toastr.error('Please Provide all details of Product.');
			  return false;
		}
	var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	  if(!regex.test(email_id)) {
		  toastr.error('Please Enter a valid Email.');
	  return false;
	  }
	 $('#shipping-pop-up').modal('hide');
	 Swal.fire('Please wait');
       Swal.showLoading();
    var cat = $.ajax({
	url:  "{{route('create.order.tracking')}}",
	type: 'POST',
	dataType: 'json',
	headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		},
	data: $(obj).parents('form:first').serialize(),
	success: function(json){
		
			if(json  == "" || json == null)
			{
		
			var icon = 'success';
			var cencel =  false;
			var text = 'Order create shipping Seccesfully';
			
			
			}
			else{
			var icon = 'error';
			var cencel =  true;
			var text = json;
			}
			Swal.fire({
			icon: icon,
			text: text,
			showCloseButton: cencel,
			allowOutsideClick: false, 
			showConfirmButton: true,
			}).then((result) => {
				console.log(result);
			if (result.isConfirmed) {
			window.location.reload();
			}
			});

		}
		});
}
	
</script>
@endpush