routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ShippingChargeController;
use App\Http\Controllers\ShippingAreaController;
use App\Http\Controllers\FrontImageController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ExcelImportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

Route::get('/', function () {
    return view('front.wellcome');
});
// routes for mobile application
Route::get('/privacy-policy/app', function () {
	return view('privacy-policy');
});
Route::get('/terms-condition/app', function () {
	return view('termCondition');
});
		Route::post('login', [AuthController::class, 'login'])->name('custom.login');
		Route::post('register', [AuthController::class, 'register'])->name('user.register');
	
	
    Route::get('return-cashfree', [HomeController::class,'returnCashFree'])->name('return.cashefree');
	Route::post('notify-cashfree', [HomeController::class,'notifyPayment'])->name('notify.cashefree');
    Route::get('refresh/captcha', [HomeController::class, 'refreshCaptcha'])->name('refresh.captcha');
    Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');
   // Route::get('self-pickup', [HomeController::class, 'selfPickup'])->name('self.pickup');
    Route::get('time', [ShippingChargeController::class, 'timeCheck'])->name('get.time');
	Route::get('razorpay-create', [HomeController::class,'getRazorpayGateway'])->name('razorpay.payment.get');
    Route::middleware(['auth:sanctum', 'verified'])->group(function (){
	Route::get('dashboard', [HomeController::class, 'mainDashboard'])->name('dashboard');
	Route::get('address-data', [OrderController::class, 'addressData'])->name('address.data');
	Route::post('order-tracking', [OrderController::class, 'orderCreateTracking'])->name('create.order.tracking');
	Route::post('cancel', [OrderController::class, 'CancelOrder'])->name('order.status');
	Route::post('accept', [OrderController::class, 'acceptOrder'])->name('accept.order');
	Route::post('Shipping/vendor', [OrderController::class, 'shippingUpdate'])->name('shipping.update');
	Route::post('Shipping-address-update', [OrderController::class, 'shippingStatusUpdate'])->name('shipping-address-update');
	Route::get('/find-user/{id}/', [UserController::class, 'userName']);
	Route::resource('address', AddressController::class);
	//Route::get('address-edit', [AddressController::class, 'addressEdit'])->name('address.edit');
	Route::post('new-address-store', [AddressController::class, 'addressAdd'])->name('new.address.store');
	Route::get('user/edit/address/{id}', [AddressController::class, 'Editaddress'])->name('editadr');
	Route::get('user/delete/address/{id}', [AddressController::class, 'DeleteAddress'])->name('deleteadr');
	Route::post('add-delete', [HomeController::class, 'addDelete'])->name('add.delete');
     
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('order-item-{id}', [HomeController::class,'viewItems'])->name('views.items');
	Route::get('my-order/list', [OrderController::class, 'userOderList'])->name('user.order.list');
	Route::get('myprofile', [UserController::class, 'MyProfile'])->name('myprofile.index');
});
Route::middleware('admin')->group(function (){
		Route::get('export-product', [HomeController::class, 'exportProduct'])->name('export.product');
		Route::put('selfprofile/{id}', [HomeController::class, 'selfProfile'])->name('self.update');
	    Route::post('file-uplaod', [HomeController::class, 'uplaodFile'])->name('file.upload');
	    Route::delete('queries-destroy{id}', [HomeController::class, 'queryDestroy'])->name('query.destroy');
	    Route::get('update-status{id}', [HomeController::class, 'updateStatus'])->name('status.update.query');
	    
	    Route::get('query', [HomeController::class, 'queryIndex'])->name('query.index');
		Route::resource('area', ShippingAreaController::class);
		Route::resource('faqs', FaqController::class);
		Route::resource('frontimage', FrontImageController::class);
		Route::resource('charge', ShippingChargeController::class);
		Route::resource('user', UserController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('faqs.dataTable', [FaqController::class, 'faqdataTable'])->name('faqs.dataTable');
		Route::resource('brand', BrandController::class);
		Route::resource('category', CategoryController::class);
		Route::get('cat.dataTable', [CategoryController::class, 'dataTable'])->name('cat.dataTable');
		Route::resource('blog', BlogController::class);
		Route::get('user.dataTable', [UserController::class, 'dataTable'])->name('user.dataTable');
		Route::get('blog-datatable', [BlogController::class, 'dataTable'])->name('blog.dataTable');
		Route::resource('product', ProductController::class);
		Route::get('product.dataTable', [ProductController::class, 'dataTable'])->name('product.dataTable');
		Route::get('get-variant', [ProductController::class, 'variantData'])->name('variant.get.data');
		Route::resource('settings', SettingsController::class);
		Route::post('settings/update', [SettingsController::class, 'update'])->name('setting.update');
		Route::resource('order', OrderController::class);
		Route::get('/product-variant/{pvt}/', [OrderController::class, 'variantName']);
		Route::resource('page', PageController::class);    
		Route::get('page-datatable', [PageController::class,'dataTable'])->name('page.dataTable');
		Route::post('images-file/{foldername}', [PageController::class,'uploadImages'])->name('page.imageupload');
		Route::get('variant.found', [OrderController::class, 'variantFound'])->name('variant.found');
        Route::get('order-invoice/{id}', [OrderController::class, 'orderinvoice'])->name('order.invoice');
		Route::get('order-dataTable', [OrderController::class, 'dataTable'])->name('order.dataTable');
		Route::get('allorder-dataTable', [OrderController::class, 'allOrderdataTable'])->name('allorder.dataTable');
		Route::get('variant-dataTable', [ProductController::class, 'varianDataTable'])->name('variant.dataTable');
		Route::get('get-variant-data', [OrderController::class, 'getVariant'])->name('variant.data');
		Route::get('specific-user}', [UserController::class, 'specificUser'])->name('specific.user');
		Route::resource('notification', NotificationController::class);
		//Route::get('admin-seen-notification', [NotificationController::class, 'adminSeenNotification'])->name('adminSeenNoti');
	Route::get('all-notification', [NotificationController::class, 'allNoti'])->name('allNoti');
	Route::get('notification-datatable', [NotificationController::class, 'dataTable'])->name('notification.dataTable');
	//Route::get('get-notification', [NotificationController::class, 'getNotification'])->name('get.notification');
	Route::get('/import-excel', [ExcelImportController::class,'index']);
	Route::post('/import-excel', [ExcelImportController::class,'import'])->name('import.excel');
});
		
         Route::get('test', [HomeController::class, 'test'])->name('test');
         Route::get('shop', [HomeController::class, 'shop'])->name('shop');
		 Route::get('favorite-product', [HomeController::class, 'favoriteProduct'])->name('favorite.product');
         Route::get('offer-product', [HomeController::class, 'offer'])->name('offer');
		 Route::get('contact/{url}', [HomeController::class, 'contactUser'])->name('contact.user');
		 Route::get('check-coupon', [CouponController::class, 'checkCoupon'])->name('cart.checkcoupon');
		 Route::get('delete-coupon', [CouponController::class, 'deleteCoupon'])->name('delete.order.coupon');
		 Route::get('cart', [HomeController::class, 'cart'])->name('cart');
		 Route::get('products/category/{url}', [HomeController::class, 'categoryCat'])->name('catCat');
		 Route::get('faq', [HomeController::class, 'faq'])->name('faq');
		 Route::get('{url}', [HomeController::class,'staticPage'])->name('static');
		 Route::post('subscribe', [HomeController::class, 'subscribe'])->name('subscribe');
		 Route::post('add-cart', [HomeController::class, 'addToCart'])->name('add.cart');
		 Route::get('product/detail/{slu}', [HomeController::class, 'ProductDetail'])->name('detail.product');
		 Route::get('brands/{name}/', [HomeController::class, 'brandProducts'])->name('brand.product');
		 Route::post('/', [HomeController::class,'inquiryVP'])->name('inquiry.product');
		 Route::post('createOrder/order', [HomeController::class, 'createOrder'])->name('createOrder');
		 Route::post('remove/cart', [HomeController::class, 'removeCart'])->name('remove.cart');
		 Route::post('add-favorite', [HomeController::class, 'addFavorite'])->name('add.favorite');
		 
		 Route::post('sendmail', [HomeController::class, 'sendEmail'])->name('sendmail.user');
		Route::post('shipping-charge', [HomeController::class, 'getShiping'])->name('shippingCharge');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Common;
use Auth,File,DB;



class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = Category::orderBy('id','desc')->get();
        return view('admin.categories.index')->with(['models' => $models]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
		
    {
        $categories=Common::getParentIdList();
        return view('admin.categories.create')->with(['categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $models = new Category;
		$url=Common::slugify($request->name);
		$request->merge(['slug' => $url]);
        $validator = $models->validator($request);
        
        if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput(); 
		$id = Auth::user()->id;
        $data=$request->all();
		    $imageName="";
			if($request->image!='')
			{
     		  $imageName=$request->image;
              File::move(public_path('temp/'.$imageName), public_path('uploads/categories/'.$imageName));
			  $path=asset('uploads/categories/'.$imageName);
			//  dd($path);
			 $models['image ']= $path;
			}
			
        if ($models->create($data)) {
            $request->session()->flash('success', 'Category added successfully.');
        } else {
            $request->session()->flash('error', 'Something went wrong. Please try again in a few minutes.');
        }
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories=Common::getParentIdList();
        return view('admin.categories.edit')->with(['model' => $category,'categories'=>$categories  ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $validator = $category->validator($request, $category->id);
        if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput();
          $data=$request->except('_token');
		  if($request->image!='')
			{
				$filePath=public_path('uploads/categories/'.$category->image);
				if (File::exists($filePath)) {
				File::delete($filePath);
				}	
     		  $imageName=$request->image;
              File::move(public_path('temp/'.$imageName), public_path('uploads/categories/'.$imageName));
			  $path=asset('uploads/categories/'.$imageName);
			  $data['image']= $path;
			}
			elseif($request->remove_image && $request->remove_image=="y")
			{
				$filePath=public_path('uploads/categories/'.$category->image);
				if (File::exists($filePath)) {
				File::delete($filePath);
				}
			   $data['image']="";
			}
		
        if ($category->fill($data)->push()) {
            $request->session()->flash('success', 'Categories updated successfully.');
        } else {
            $request->session()->flash('error', 'Something went wrong. Please try again in a few minutes.');
        }
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,Category $category)
    {
        try 
        {
           if ($category->delete()) {
                $request->session()->flash('success', 'Category deleted successfully.');
            }

        } catch (Exception $e) {
          $request->session()->flash('error', 'Something went wrong. Please try again in a few minutes.');
        }
       return redirect()->route('category.index');
	}
	public function dataTable(Category $category)
    {
		   $offset=0;
	       $limit=10;
           $user=Auth::user();
			$userID=$user->id;
			$where="where 1";
				$catId=$_GET['cat_id'];
				if($catId >0)
				{
					$where= "where parent_id=".$catId;
				}
			
           $serachStrText=stripslashes($_GET['search']['value']); 	
           $order=" ORDER BY `id` DESC";		   
	       if(isset($_GET['start']) && $_GET['start']!='')
		   {
			   $offset=$_GET['start'];
		   }
		   if(isset($_GET['length']) && $_GET['length']!='')
		   {
			   $limit=$_GET['length'];
		   }
            if($serachStrText!='')
			{
			  $alTextA=explode(' ',$serachStrText);
			  foreach($alTextA as $serachStr)
			   {				
				$serachStr=addslashes($serachStr);
				$whereArray=[];                   
				$whereArray[]="name like '%".$serachStr."%'";		
				$where.=" and (".implode(' or ',$whereArray).")";
			   }
            }						
			$slectQuery="SELECT * FROM categories ".$where;
		     $contractsCnt=DB::select($slectQuery);
			 $total_records=count($contractsCnt);			 
			 $category=DB::select($slectQuery." order by id desc limit ".$offset.",".$limit);//." limit ".$offset.",".$limit
			 $AllData=[];
			$category=Category::hydrate($category);				 
			 foreach($category as $cat)
			 {
				$data=[];
				if(!empty($cat->image) || $cat->image != null )
				{
				$data[]='<img height="50px" src=" '.$cat->image.' ">';
				}else{
					$data[]='<div class="red">No Image</div>';
				}
				if($cat->parent_id>0)
				{
				$data[]= ucwords($cat->parentName());
				$data[]=ucwords($cat->name);
				}else{
				$data[]=ucwords($cat->name);
				$data[]="-";
				}
				$data[]=$cat->slug;
				$data[]=$cat->status== 1?"Active":"InActive";
                $delete=route('category.destroy',$cat->id);
                $edit=route('category.edit',$cat->id);
				$editimage=asset('img/datatable-edit-plus.svg');
				$deleteImage=asset('img/datatable-delete.svg');
				
                $btn='<a href="'.$edit.'" class="btn me-2 dataActionBtn btnEdit"  title="Edit"><img src="'.$editimage.'" alt="" /></a> <a href="javascript:void(0);" class="btn me-2 dataActionBtn btnDelete" title="Delete" onclick="deleteCategory(this)" data-href="'.$delete.'"><img src="'.$deleteImage.'" alt="" /></a> ';
	
                $data[]='<div class="d-flex justify-content-start">'.$btn.'</div>';	
				$AllData[]=$data;
			}
			 $draw=(isset($_GET['draw'])?$_GET['draw']:0);
		return json_encode(array('draw'=>$draw,"recordsTotal"=>$total_records,"recordsFiltered"=> $total_records,"data"=>$AllData));
    }
    
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="pageTtl">
            <h1>Add Categeory</h1>
        </div>      
<div class="greyBx">
            <div class="innerWrap"> 
               

                {{ Form::open(['route' => 'category.store','enctype'=>"multipart/form-data"]) }}

                    {{ csrf_field() }} 
                                      
                    @include('admin.categories.form') 

                {{ Form::close() }}
           
                </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="pageTtl">
            <h1>Edit Categeory</h1>
			</div>
<div class="greyBx">
            <div class="innerWrap">	
              {{ Form::model($model,['route' => ['category.update', $model->id],'enctype'=>"multipart/form-data"]) }}

                    {{ csrf_field() }}
                    @method('PUT')
                    @include('admin.categories.form')            

                {{ Form::close() }}
           
                </div>
    </div>

@endsection

resources/views/admin/categories/form.blade.php
<?php
use App\Models\Category;
$menuList=Category::where('parent_id',null)->pluck('id');
$oldfile="";
 if(isset($model) && $model->image!='')
 {
	 $oldfile=$model->image;
 }	
?>

	<div class="col-md-12">
	  <div class="row">
		<div class="mb-2rem col-md-6 {{ $errors->has('parent_id') ? 'has-error' : '' }}">
		  <label for="parent_id" class="form-label"> CATEGEORY</label>
      {{ Form::select('parent_id', $categories, null, ['id'=>'parent_id','onchange'=>'catValue(this)','class' => 'form-control','placeholder'=>'Main Cateogory']) }}
			@if ($errors->has('parent_id'))
				<span class="help-block">
					<strong>{{ $errors->first('parent_id') }}</strong>
				</span>
			@endif
		</div>
		<div class="mb-2rem col-md-6  {{ $errors->has('name') ? 'has-error' : '' }}">
		  <label for="name" class="form-label">NAME <span class="red"> *</span></label>
      {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control', 'placeholder' => 'Name', 'value' => old('name')]) !!}
			@if ($errors->has('name'))
				<span class="help-block">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
			@endif
		 </div>		
		</div>
	 </div>
	<div class="col-md-12">
	  <div class="row">
	    <div class="mb-2rem col-md-6  {{ $errors->has('name') ? 'has-error' : '' }}">
		  <label for="position" class="form-label">POSITION</label>
      {!! Form::text('position', null, ['id' => 'position', 'class' => 'form-control', 'placeholder' => 'position', 'value' => old('position')]) !!}
			@if ($errors->has('position'))
				<span class="help-block">
					<strong>{{ $errors->first('position') }}</strong>
				</span>
			@endif
		 </div>	
		
		<div class="mb-2rem col-md-6 {{ $errors->has('status') ? 'has-error' : '' }}">
		  <label for="status" class="form-label">STATUS</label>
      {{ Form::select('status', ['1'=>'Active','0'=>'InActive'],null, ['class' => 'form-select']) }}
			@if ($errors->has('status'))
				<span class="help-block">
					<strong>{{ $errors->first('status') }}</strong>
				</span>
			@endif
		</div>	
		 </div>
		</div>
		<div class="col-md-12">
	  <div class="row">
		<div class="mb-2rem col-md-6 {{ $errors->has('image') ? 'has-error' : '' }}">
      @include('admin.image-uploader',['label'=>'Image','key'=>'image','oldfile'=>$oldfile])
			@if ($errors->has('image'))
				<span class="help-block">
					<strong>{{ $errors->first('image') }}</strong>
				</span>
			@endif
		</div>	
		
		 <div class="mb-2rem col-md-6 {{ $errors->has('show_list') ? 'has-error' : '' }}" id="menu_data">
		  <label for="show_list" class="form-label">Show List <input type="checkbox" name="show_list" @if('checked') value="1" @endif @if(isset($model) && $model->show_list == 1 ) checked @endif /></label>
      
		</div>
		<div class="col-md-12">
			<div class="row">
				<div class="mb-2rem col-md-6 {{ $errors->has('meta_title') ? 'has-error' : '' }}">
					<label for="meta_title" class="form-label">Meta Title</label>
					{{ Form::text('meta_title',  null, ['class' => 'form-control','placeholder'=>'Meta Title','id'=>'meta_title','value' => old('meta_title')]) }}
					@if ($errors->has('meta_title'))
					<span class="help-block">
						<strong>{{ $errors->first('meta_title') }}</strong>
					</span>
					@endif
				</div>
				<div class="mb-2rem col-md-6 {{ $errors->has('meta_tag') ? 'has-error' : '' }}">
					<label for="meta_tag" class="form-label">Meta Keyword</label>
					{{ Form::text('meta_tag',null, ['class' => 'form-control','placeholder'=>'Meta Keywords','value' => old('meta_tag'),'id'=>'meta_tag']) }}
					@if ($errors->has('meta_tag'))
					<span class="help-block">
						<strong>{{ $errors->first('meta_tag') }}</strong>
					</span>
					@endif
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="row">
				<div class="mb-2rem col-md-12 {{ $errors->has('meta_description') ? 'has-error' : '' }}">
					<label for="meta_description" class="form-label">Meta Description</label>
					{{ Form::textarea('meta_description',null, ['class' => 'form-control','placeholder'=>'Write somthing here............','value' => old('meta_description'),'id'=>'meta_description']) }}
					@if ($errors->has('meta_description'))
					<span class="help-block">
						<strong>{{ $errors->first('meta_description') }}</strong>
					</span>
					@endif
				</div>
			</div>
		</div>
		</div>
		</div>
			<div class="d-flex justify-content-start ">
	  <button type="submit" class="btn btn-primary themeBtn themeFill me-3">Submit</button>
	   <a  href="{{ url()->previous() }}" class="btn btn-primary themeBtn themeUnFill">Cancel</a>
	   <!--<a type="button" class="btn btn-primary themeBtn themeUnFill me-3" data-bs-dismiss="modal" aria-label="Close">Cancel</a>-->
	</div>
@push('scripts')
<script type="text/javascript">
//var menuList = { !! $menuList !!};
var filepath="{{route('file.upload')}}";
$('document').ready(function(){
	if($('#image').length>0)
	{
		//$('#submitButton').hide();
	  addDropZone('image',filepath);
	}
});
	
 
</script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@section('content')
<?php
use App\Models\Category;
$category=Category::where('parent_id',null)->get();
?>
<div class="themeTable">
          <div class="table_id DatatableHeader" >
            <div class="pgTitle">
              <h1>Category</h1>
            </div>
            <div class="searchBx">
              <input type="text" id="myInputTextField" placeholder="Search">
            </div>
			&nbsp;&nbsp;
			<div class="col-md-3 pull-right searchBx" >
					<select id='cat_id'class="form-control searchBx">
					    <option value="0" >Select Main Catgeory</option>
					 @foreach($category as $key=>$cat)
							<option value="{{$cat->id}}">{{$cat->name}}</option>
					@endforeach
					</select>
            </div>
            <div class="tableLength">
		    <a href="{{route('category.create')}}" class="btn btn-primary themeBtn themeFill iconLeft">
                
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 8.69814H6.56325V15.261H8.69814V8.69814H15.261V6.56322H8.69814V0H6.56325V6.56322H0V8.69814Z" fill="white"/>
                </svg>
                &nbsp; Add new</a>
            </div>
          </div>
          
          <div class="table-responsive">
            <table id="listtable1" class="display table table-striped">
			 <thead>
                <tr>
                    <th>Image</th>
				    <th>Main Category</th>
                    <th>Child Category</th>
                    <th>Slug</th> 
                    <th>Status</th> 
                    <th>Action</th>					
                    
                </tr>
            </thead>
            <tbody>
			
			 </tbody>
            </table>
          </div>
      </div>

@endsection
@push('scripts')
<script type="text/javascript">
var catTable;
$( document ).ready(function() {
	catTable=$('#listtable1').DataTable({
			responsive: true,
			processing: true,
			serverSide: true,
			searching: true,
			ajax:  {
				"url":"{{route('cat.dataTable')}}",
				"data": function(data){
					data.cat_id = $('#cat_id').val();
				}
			},
			stateSave: true,
			bLengthChange: true,
			bInfo: true,

		});
		$('#myInputTextField').keyup(function(){
		catTable.search($(this).val()).draw() ;
		});
		$('#cat_id').change(function(){
			catTable.draw();
		});

} );
function deleteCategory(obj)
{
  var url = $(obj).data('href');
	$('#confirm-delete .modal-title').html('Delete Category');
    $('#confirm-delete form').attr('action',url);
	$('#confirm-delete .text-center').html('Are you sure want to delete this Category?');
	$('#confirm-delete').modal('show');
}
</script>
@endpush